[package]
name = "public_private_keys"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39 = { version = "2.1.0", features = ["rand"]}
bs58 = "0.5.1"
ed25519-hd-key = "0.3.0"
ethers = "2.0.14"
hex = "0.4.3"
solana-sdk = "2.3.0"
tokio = { version = "1.45.1", features = ["full"] }
